flowchart TD
  start    --> pokebola 
  start    --> pokemon 
  pokebola --> Pointer --> pu1[pokemon]
  pokemon  --> t1["$$\times$$"]
  t1       --> c1[","]
  c1       --> pi
  c1       --> float 
  t1       --> t2["$$\times$$"]
  t2       --> c2[","]
  c2       --> ka
  c2       --> aux["pokebola"]
  t2       --> c3[","]
  c3       --> chu
  c3       --> aux2["pokebola"]
